# Generated by Django 6.0 on 2025-12-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='languge',
            new_name='language',
        ),
    ]
