# Generated by Django 6.0 on 2025-12-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_languge_snippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
