# Generated by Django 6.0 on 2025-12-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_category_todo_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('during', 'During'), ('done', 'Done'), ('canceled', 'Canceled'), ('blocked', 'Blocked')], default='planned', max_length=10),
        ),
    ]
