# Generated by Django 6.0 on 2025-12-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_offer_created_at_offer_is_published'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
