# Generated by Django 6.0 on 2025-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_offer_tags'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
