# Generated by Django 6.0 on 2025-12-11 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.offer')),
            ],
        ),
    ]
